/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeOps */

#ifndef _Included_NativeOps
#define _Included_NativeOps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeOps
 * Method:    factorial
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_NativeOps_factorial
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
